import { LetterData } from './types';

export const VIETNAMESE_ALPHABET: LetterData[] = [
  {
    letter: "A",
    uppercase: "A",
    lowercase: "a",
    word: "Cái Ca",
    phoneticWord: "ca (cờ - a - ca)",
    pronunciation: "A",
    exampleWord: "ca",
    iconName: "CupSoda",
    color: "bg-rose-50 border-rose-200 text-rose-700 hover:bg-rose-100",
    badgeColor: "bg-rose-100 text-rose-800",
    textAccentColor: "text-rose-600",
    desc: "Bé dùng cái ca này để múc nước uống nước nhé!",
    tracingPoints: ["M 30,80 L 50,20 L 70,80", "M 40,55 L 60,55"] // Standard A capital tracing strokes
  },
  {
    letter: "Ă",
    uppercase: "Ă",
    lowercase: "ă",
    word: "Con Rắn",
    phoneticWord: "rắn (rờ - ăn - răn - sắc - rắn)",
    pronunciation: "Á",
    exampleWord: "rắn",
    iconName: "Activity",
    color: "bg-amber-50 border-amber-200 text-amber-700 hover:bg-amber-100",
    badgeColor: "bg-amber-100 text-amber-800",
    textAccentColor: "text-amber-600",
    desc: "Chú rắn uốn lượn đáng yêu nhưng nhớ tránh xa nhé bé!",
    tracingPoints: ["M 30,80 L 50,20 L 70,80", "M 40,55 L 60,55", "M 40,12 Q 50,18 60,12"] // A + breve stroke
  },
  {
    letter: "Â",
    uppercase: "Â",
    lowercase: "â",
    word: "Cái Ấm",
    phoneticWord: "ấm (ớ - mờ - âm - sắc - ấm)",
    pronunciation: "Ớ",
    exampleWord: "ấm",
    iconName: "Coffee",
    color: "bg-yellow-50 border-yellow-200 text-yellow-700 hover:bg-yellow-100",
    badgeColor: "bg-yellow-100 text-yellow-800",
    textAccentColor: "text-yellow-600",
    desc: "Chiếc ấm đun nước pha trà thơm phức cho ông bà.",
    tracingPoints: ["M 30,80 L 50,20 L 70,80", "M 40,55 L 60,55", "M 40,15 L 50,7 L 60,15"] // A + circumflex
  },
  {
    letter: "B",
    uppercase: "B",
    lowercase: "b",
    word: "Quả Bóng",
    phoneticWord: "bóng (bờ - ong - bong - sắc - bóng)",
    pronunciation: "Bờ",
    exampleWord: "bóng",
    iconName: "Dribbble",
    color: "bg-lime-50 border-lime-200 text-lime-700 hover:bg-lime-100",
    badgeColor: "bg-lime-100 text-lime-800",
    textAccentColor: "text-lime-600",
    desc: "Quả bóng tròn xoe để bé đá bóng cùng các bạn nào!",
    tracingPoints: ["M 35,20 L 35,80", "M 35,20 Q 65,20 65,50 Q 35,50 35,50", "M 35,50 Q 70,50 70,80 Q 35,80 35,80"]
  },
  {
    letter: "C",
    uppercase: "C",
    lowercase: "c",
    word: "Con Cá",
    phoneticWord: "cá (cờ - a - ca - sắc - cá)",
    pronunciation: "Cờ",
    exampleWord: "cá",
    iconName: "Fish",
    color: "bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100",
    badgeColor: "bg-emerald-100 text-emerald-800",
    textAccentColor: "text-emerald-600",
    desc: "Chú cá nhỏ bơi lội tung tăng trong làn nước mát.",
    tracingPoints: ["M 65,30 C 55,15 35,20 35,50 C 35,80 55,85 65,70"]
  },
  {
    letter: "D",
    uppercase: "D",
    lowercase: "d",
    word: "Quả Dừa",
    phoneticWord: "dừa (dờ - ưa - dưa - huyền - dừa)",
    pronunciation: "Dờ",
    exampleWord: "dừa",
    iconName: "Disc",
    color: "bg-teal-50 border-teal-200 text-teal-700 hover:bg-teal-100",
    badgeColor: "bg-teal-100 text-teal-800",
    textAccentColor: "text-teal-600",
    desc: "Trái dừa ngọt lịm có nước dừa mát lành giải khát ngày hè.",
    tracingPoints: ["M 35,20 L 35,80", "M 35,20 C 65,20 65,80 35,80"]
  },
  {
    letter: "Đ",
    uppercase: "Đ",
    lowercase: "đ",
    word: "Cây Đàn",
    phoneticWord: "đàn (đờ - an - đan - huyền - đàn)",
    pronunciation: "Đờ",
    exampleWord: "đàn",
    iconName: "Music",
    color: "bg-cyan-50 border-cyan-200 text-cyan-700 hover:bg-cyan-100",
    badgeColor: "bg-cyan-100 text-cyan-800",
    textAccentColor: "text-cyan-600",
    desc: "Cây đàn phát ra những âm thanh réo rắt vui tai ghê!",
    tracingPoints: ["M 40,20 L 40,80", "M 40,20 C 70,20 70,80 40,80", "M 25,50 L 55,50"]
  },
  {
    letter: "E",
    uppercase: "E",
    lowercase: "e",
    word: "Em Bé",
    phoneticWord: "bé (bờ - e - be - sắc - bé)",
    pronunciation: "E",
    exampleWord: "bé",
    iconName: "Baby",
    color: "bg-sky-50 border-sky-200 text-sky-700 hover:bg-sky-100",
    badgeColor: "bg-sky-100 text-sky-800",
    textAccentColor: "text-sky-600",
    desc: "Em bé cười toe toét thật là đáng yêu thương biết bao!",
    tracingPoints: ["M 65,20 L 35,20 L 35,80 L 65,80", "M 35,50 L 60,50"]
  },
  {
    letter: "Ê",
    uppercase: "Ê",
    lowercase: "ê",
    word: "Con Ếch",
    phoneticWord: "ếch (ê - chờ - êch - sắc - ếch)",
    pronunciation: "Ê",
    exampleWord: "ếch",
    iconName: "Smile",
    color: "bg-indigo-50 border-indigo-200 text-indigo-700 hover:bg-indigo-100",
    badgeColor: "bg-indigo-100 text-indigo-800",
    textAccentColor: "text-indigo-600",
    desc: "Chú ếch xanh ngồi trên lá sen kêu ộp ộp đón mưa rào.",
    tracingPoints: ["M 65,25 L 35,25 L 35,80 L 65,80", "M 35,50 L 60,50", "M 42,12 L 50,5 L 58,12"]
  },
  {
    letter: "G",
    uppercase: "G",
    lowercase: "g",
    word: "Quả Gấc",
    phoneticWord: "gấc (gờ - ac - gac - sắc - gấc)",
    pronunciation: "Gờ",
    exampleWord: "gấc",
    iconName: "Egg",
    color: "bg-violet-50 border-violet-200 text-violet-700 hover:bg-violet-100",
    badgeColor: "bg-violet-100 text-violet-800",
    textAccentColor: "text-violet-600",
    desc: "Quả gấc đỏ rực giúp nấu món xôi gấc thơm ngon, bổ mắt.",
    tracingPoints: ["M 65,30 C 55,15 35,20 35,50 C 35,80 55,85 65,70 L 65,50 L 48,50"]
  },
  {
    letter: "H",
    uppercase: "H",
    lowercase: "h",
    word: "Bông Hoa",
    phoneticWord: "hoa (hờ - oa - hoa)",
    pronunciation: "Hờ",
    exampleWord: "hoa",
    iconName: "Flower",
    color: "bg-purple-50 border-purple-200 text-purple-700 hover:bg-purple-100",
    badgeColor: "bg-purple-100 text-purple-800",
    textAccentColor: "text-purple-600",
    desc: "Bông hoa nở rộ khoe sắc thắm dưới ánh nắng ban mai.",
    tracingPoints: ["M 35,20 L 35,80", "M 65,20 L 65,80", "M 35,50 L 65,50"]
  },
  {
    letter: "I",
    uppercase: "I",
    lowercase: "i",
    word: "Viên Bi",
    phoneticWord: "bi (bờ - i - bi)",
    pronunciation: "I",
    exampleWord: "bi",
    iconName: "Circle",
    color: "bg-fuchsia-50 border-fuchsia-200 text-fuchsia-700 hover:bg-fuchsia-100",
    badgeColor: "bg-fuchsia-100 text-fuchsia-800",
    textAccentColor: "text-fuchsia-600",
    desc: "Viên bi tròn lấp lánh cho bé chơi trò bắn bi thật vui nhộn.",
    tracingPoints: ["M 50,20 L 50,80", "M 40,20 L 60,20", "M 40,80 L 60,80"]
  },
  {
    letter: "K",
    uppercase: "K",
    lowercase: "k",
    word: "Cái Kéo",
    phoneticWord: "kéo (ca - eo - keo - sắc - kéo)",
    pronunciation: "Ca",
    exampleWord: "kéo",
    iconName: "Scissors",
    color: "bg-pink-50 border-pink-200 text-pink-700 hover:bg-pink-100",
    badgeColor: "bg-pink-100 text-pink-800",
    textAccentColor: "text-pink-600",
    desc: "Cái kéo nhỏ xinh để cắt giấy thủ công xếp hạc giấy nha.",
    tracingPoints: ["M 35,20 L 35,80", "M 65,20 L 35,50 L 65,80"]
  },
  {
    letter: "L",
    uppercase: "L",
    lowercase: "l",
    word: "Chiếc Lá",
    phoneticWord: "lá (lờ - a - la - sắc - lá)",
    pronunciation: "Lờ",
    exampleWord: "lá",
    iconName: "Leaf",
    color: "bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100",
    badgeColor: "bg-emerald-100 text-emerald-800",
    textAccentColor: "text-emerald-600",
    desc: "Chiếc lá xanh đón gió trời đung đưa xào xạc ngoài vườn.",
    tracingPoints: ["M 35,20 L 35,80 L 65,80"]
  },
  {
    letter: "M",
    uppercase: "M",
    lowercase: "m",
    word: "Con Mèo",
    phoneticWord: "mèo (mờ - eo - meo - huyền - mèo)",
    pronunciation: "Mờ",
    exampleWord: "mèo",
    iconName: "Cat",
    color: "bg-amber-50 border-amber-200 text-amber-700 hover:bg-amber-100",
    badgeColor: "bg-amber-100 text-amber-800",
    textAccentColor: "text-amber-600",
    desc: "Chú mèo lười thích sưởi nắng kêu meo meo nũng nịu lắm.",
    tracingPoints: ["M 30,80 L 30,20 L 50,55 L 70,20 L 70,80"]
  },
  {
    letter: "N",
    uppercase: "N",
    lowercase: "n",
    word: "Cây Nấm",
    phoneticWord: "nấm (nờ - âm - nâm - sắc - nấm)",
    pronunciation: "Nờ",
    exampleWord: "nấm",
    iconName: "Gift",
    color: "bg-orange-50 border-orange-200 text-orange-700 hover:bg-orange-100",
    badgeColor: "bg-orange-100 text-orange-800",
    textAccentColor: "text-orange-600",
    desc: "Cây nấm nhỏ mọc trong rừng sâu xòe ô che mưa bé xíu.",
    tracingPoints: ["M 30,80 L 30,20 L 70,80 L 70,20"]
  },
  {
    letter: "O",
    uppercase: "O",
    lowercase: "o",
    word: "Quả Nho",
    phoneticWord: "nho (nhờ - o - nho)",
    pronunciation: "O",
    exampleWord: "nho",
    iconName: "Bug",
    color: "bg-rose-50 border-rose-200 text-rose-700 hover:bg-rose-100",
    badgeColor: "bg-rose-100 text-rose-800",
    textAccentColor: "text-rose-600",
    desc: "O tròn như quả trứng gà, những chùm nho căng mọng mọc trĩu cành.",
    tracingPoints: ["M 50,20 C 30,20 30,80 50,80 C 70,80 70,20 50,20"]
  },
  {
    letter: "Ô",
    uppercase: "Ô",
    lowercase: "ô",
    word: "Cái Ô",
    phoneticWord: "ô (ô)",
    pronunciation: "Ô",
    exampleWord: "ô",
    iconName: "Umbrella",
    color: "bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100",
    badgeColor: "bg-blue-100 text-blue-800",
    textAccentColor: "text-blue-600",
    desc: "Ô thì đội mũ, cái ô che mưa che nắng che cả mây trời.",
    tracingPoints: ["M 50,25 C 30,25 30,85 50,85 C 70,85 70,25 50,25", "M 42,12 L 50,5 L 58,12"]
  },
  {
    letter: "Ơ",
    uppercase: "Ơ",
    lowercase: "ơ",
    word: "Quả Ớt",
    phoneticWord: "ớt (ơ - tờ - ơt - sắc - ớt)",
    pronunciation: "Ơ",
    exampleWord: "ớt",
    iconName: "Flame",
    color: "bg-red-50 border-red-200 text-red-700 hover:bg-red-100",
    badgeColor: "bg-red-100 text-red-800",
    textAccentColor: "text-red-600",
    desc: "Ơ thì thêm râu, quả ớt nhỏ xinh màu đỏ rực cay cay cay.",
    tracingPoints: ["M 48,25 C 28,25 28,85 48,85 C 68,85 68,25 48,25", "M 60,25 Q 67,20 63,14"]
  },
  {
    letter: "P",
    uppercase: "P",
    lowercase: "p",
    word: "Cục Pin",
    phoneticWord: "pin (pờ - i - nờ - pin)",
    pronunciation: "Pờ",
    exampleWord: "pin",
    iconName: "Battery",
    color: "bg-neutral-50 border-neutral-200 text-neutral-700 hover:bg-neutral-100",
    badgeColor: "bg-neutral-200 text-neutral-800",
    textAccentColor: "text-neutral-600",
    desc: "Cục pin dồi dào năng lượng giúp chiếc xe đồ chơi chạy thật nhanh.",
    tracingPoints: ["M 35,20 L 35,80", "M 35,20 Q 65,20 65,50 Q 35,50 35,50"]
  },
  {
    letter: "Q",
    uppercase: "Q",
    lowercase: "q",
    word: "Cái Quạt",
    phoneticWord: "quạt (quờ -at - quat - nặng - quạt)",
    pronunciation: "Quờ",
    exampleWord: "quạt",
    iconName: "Wind",
    color: "bg-purple-50 border-purple-200 text-purple-700 hover:bg-purple-100",
    badgeColor: "bg-purple-100 text-purple-800",
    textAccentColor: "text-purple-600",
    desc: "Cái quạt giấy đưa hương gió mát rượi xua tan cơn nóng nực.",
    tracingPoints: ["M 50,20 C 30,20 30,80 50,80 C 70,80 70,20 50,20", "M 62,68 L 75,85"]
  },
  {
    letter: "R",
    uppercase: "R",
    lowercase: "r",
    word: "Con Rùa",
    phoneticWord: "rùa (rờ - ua - rua - huyền - rùa)",
    pronunciation: "Rờ",
    exampleWord: "rùa",
    iconName: "Shield",
    color: "bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100",
    badgeColor: "bg-emerald-100 text-emerald-800",
    textAccentColor: "text-emerald-600",
    desc: "Bạn rùa hiền lành rụt cổ nhút nhát nhưng bò rất bền bỉ nha.",
    tracingPoints: ["M 35,20 L 35,80", "M 35,20 Q 65,20 65,50 Q 35,50 35,50", "M 35,50 L 65,80"]
  },
  {
    letter: "S",
    uppercase: "S",
    lowercase: "s",
    word: "Cuốn Sách",
    phoneticWord: "sách (sờ - ach - sach - sắc - sách)",
    pronunciation: "Sờ",
    exampleWord: "sách",
    iconName: "BookOpen",
    color: "bg-teal-50 border-teal-200 text-teal-700 hover:bg-teal-100",
    badgeColor: "bg-teal-100 text-teal-800",
    textAccentColor: "text-teal-600",
    desc: "Mở cuốn sách thơm tho ra có bao điều thú vị đón chờ bé.",
    tracingPoints: ["M 65,25 Q 35,15 35,40 Q 35,65 65,55 Q 65,80 35,85"]
  },
  {
    letter: "T",
    uppercase: "T",
    lowercase: "t",
    word: "Quả Táo",
    phoneticWord: "táo (tờ - ao - tao - sắc - táo)",
    pronunciation: "Tờ",
    exampleWord: "táo",
    iconName: "Apple",
    color: "bg-rose-50 border-rose-200 text-rose-700 hover:bg-rose-100",
    badgeColor: "bg-rose-100 text-rose-800",
    textAccentColor: "text-rose-600",
    desc: "Quả táo đỏ giòn ngọt thơm ngon, cung cấp vitamin cho bé khỏe.",
    tracingPoints: ["M 30,20 L 70,20", "M 50,20 L 50,80"]
  },
  {
    letter: "U",
    uppercase: "U",
    lowercase: "u",
    word: "Cái Muỗng",
    phoneticWord: "muỗng (mờ - uông - muông - ngã - muỗng)",
    pronunciation: "U",
    exampleWord: "muỗng",
    iconName: "GlassWater",
    color: "bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100",
    badgeColor: "bg-blue-100 text-blue-800",
    textAccentColor: "text-blue-600",
    desc: "Cái muỗng inox nhỏ xinh giúp bé tự xúc cơm ăn giỏi giang.",
    tracingPoints: ["M 30,20 L 30,65 C 30,80 70,80 70,65 L 70,20"]
  },
  {
    letter: "Ư",
    uppercase: "Ư",
    lowercase: "ư",
    word: "Lá Thư",
    phoneticWord: "thư (thờ - ư - thư)",
    pronunciation: "Ư",
    exampleWord: "thư",
    iconName: "Mail",
    color: "bg-cyan-50 border-cyan-200 text-cyan-700 hover:bg-cyan-100",
    badgeColor: "bg-cyan-100 text-cyan-800",
    textAccentColor: "text-cyan-600",
    desc: "Bức thư tay chan chứa bao lời chúc ấm áp gửi phương xa.",
    tracingPoints: ["M 30,20 L 30,65 C 30,80 70,80 70,65 L 70,20", "M 70,20 Q 77,15 73,9"]
  },
  {
    letter: "V",
    uppercase: "V",
    lowercase: "v",
    word: "Quyển Vở",
    phoneticWord: "vở (vờ - ơ - vơ - hỏi - vở)",
    pronunciation: "Vờ",
    exampleWord: "vở",
    iconName: "Notebook",
    color: "bg-pink-50 border-pink-200 text-pink-700 hover:bg-pink-100",
    badgeColor: "bg-pink-100 text-pink-800",
    textAccentColor: "text-pink-600",
    desc: "Quyển vở nhãn hoa xinh xắn để bé rèn viết từng nét chữ đầu tiên.",
    tracingPoints: ["M 30,20 L 50,80 L 70,20"]
  },
  {
    letter: "X",
    uppercase: "X",
    lowercase: "x",
    word: "Xe Đạp",
    phoneticWord: "xe (xờ - e - xe)",
    pronunciation: "Xờ",
    exampleWord: "xe",
    iconName: "Bike",
    color: "bg-teal-50 border-teal-200 text-teal-700 hover:bg-teal-100",
    badgeColor: "bg-teal-100 text-teal-800",
    textAccentColor: "text-teal-600",
    desc: "Xe đạp ba bánh có cái chuông kính coong để bé đạp dạo mát.",
    tracingPoints: ["M 30,20 L 70,80", "M 70,20 L 30,80"]
  },
  {
    letter: "Y",
    uppercase: "Y",
    lowercase: "y",
    word: "Hộp Y Tế",
    phoneticWord: "y (y)",
    pronunciation: "Y",
    exampleWord: "y tế",
    iconName: "Heart",
    color: "bg-rose-50 border-rose-200 text-rose-700 hover:bg-rose-100",
    badgeColor: "bg-rose-100 text-rose-800",
    textAccentColor: "text-rose-600",
    desc: "Hộp cứu thương có thuốc bông băng bảo vệ cả nhà khi đau ốm.",
    tracingPoints: ["M 30,20 L 50,50 L 70,20", "M 50,50 L 50,80"]
  }
];
